### ISSUE TITLE
Site offline Is the project still active?

### ISSUE THREAD

**Issue by maxmckenzie** [guifi/drupal-guifi#43]
I just heard about this project in this interview with sub.media https://www.mixcloud.com/solecast-sole/solecast-36-w-frank-lopez-on-submedias-new-documentary-series-trouble-much-more/

took a little while to find the info and the site seems to be offline. Is this project still active, do you need contributors?

**Comment by ghost** [comment]
Hi @maxmckenzie !

Now the site is running again.

Why is the drupal project going offline? Some folks told me that this is because it is a very old drupal 6 and the dependencies with the database are increasingly being corrupted. In other words: we need help!

I see in your profile that you are from Barcelona. I invite you to come to our weekly community meeting: exo.cat/guifilab

Lately we are more active in the [matrix-riot chat](https://riot.guifi.net/#/directory). [Check the info about the service](https://matrix.guifi.net/)

This is the intended development groupchat: https://riot.guifi.net/#/room/#guifi-dev-public:matrix.guifi.net

The development mailinglist regretably has very low traffic :( https://llistes.guifi.net/sympa/info/guifi-dev
